"use client"

import { useQuery } from "@tanstack/react-query"
import type { Control, FieldValues, Path } from "react-hook-form"
import { Controller, useWatch } from "react-hook-form"
import type { FieldSpec } from "@/lib/forms/types"
import { frappe } from "@/lib/frappe"
import { financeRowInput, financeRowSelect } from "@/lib/finance-ui"
import { FinancePropertyRow } from "@/components/finance/FinancePropertyPanel"
import { useEffect, useRef, useState } from "react"

/**
 * Options for a Link field spec'd with `dropdown: true` — the list of
 * records of its target doctype (`spec.options`), rather than the usual
 * type-the-exact-name Data input. Supports:
 *  - `linkStaticFilters` / `linkFilterFields`: narrows the fetched records
 *    (e.g. parent_account filtered to is_group=1 + the currently-selected
 *    company/root_type).
 *  - `linkLabelFields`: composes a readable option label from extra fields
 *    on the target doctype, for doctypes (like SMS Student) whose `name`
 *    is an opaque autogenerated hash rather than something human-readable.
 */

function LinkCombobox({
  spec,
  value,
  onChange,
  options,
  isLoading,
  disabled,
  placeholder,
}: {
  spec: FieldSpec
  value: string | undefined
  onChange: (v: string) => void
  options: Array<Record<string, unknown> & { name: string }>
  isLoading: boolean
  disabled: boolean
  placeholder?: string
}) {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState("")
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    function onClickOutside(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setOpen(false)
        setQuery("")
      }
    }
    document.addEventListener("mousedown", onClickOutside)
    return () => document.removeEventListener("mousedown", onClickOutside)
  }, [])

  const selected = options.find((o) => o.name === value)
  const displayValue = open ? query : selected ? linkOptionLabel(spec, selected) : ""
  const filtered = query
    ? options.filter((o) => linkOptionLabel(spec, o).toLowerCase().includes(query.toLowerCase()))
    : options

  return (
    <div ref={ref} className="relative">
      <input
        type="text"
        className={`rounded border border-border ${financeRowInput}`}
        placeholder={placeholder ?? (isLoading ? "Loading…" : `Search ${spec.label}`)}
        value={displayValue}
        disabled={disabled}
        onFocus={() => { setOpen(true); setQuery("") }}
        onChange={(e) => { setQuery(e.target.value); setOpen(true) }}
      />
      {open && !disabled && (
        <div className="absolute z-10 mt-1 max-h-56 w-full overflow-auto rounded border border-border bg-card shadow-md">
          {isLoading ? (
            <div className="px-2 py-1 text-sm text-muted-foreground">Loading…</div>
          ) : filtered.length === 0 ? (
            <div className="px-2 py-1 text-sm text-muted-foreground">No matches</div>
          ) : (
            filtered.map((opt) => (
              <button
                key={opt.name}
                type="button"
                className="block w-full px-2 py-1 text-left text-sm hover:bg-muted"
                onClick={() => { onChange(opt.name); setOpen(false); setQuery("") }}
              >
                {linkOptionLabel(spec, opt)}
              </button>
            ))
          )}
        </div>
      )}
    </div>
  )
}

function useLinkDropdownOptions(spec: FieldSpec, watchedFilterValues: Record<string, unknown>) {
  const enabled = spec.fieldtype === "Link" && !!spec.dropdown && !!spec.options

  const filters: Record<string, unknown> = { ...(spec.linkStaticFilters ?? {}) }
  for (const key of spec.linkFilterFields ?? []) {
    const v = watchedFilterValues[key]
    if (v) filters[key] = v
  }
  const depsSatisfied = (spec.linkFilterFields ?? []).every((key) => !!watchedFilterValues[key])

  return useQuery({
    queryKey: ["Link", "dropdown-options", spec.options, filters, spec.linkLabelFields],
    queryFn: () =>
      frappe.list<Record<string, unknown> & { name: string }>(spec.options as string, {
        fields: ["name", ...(spec.linkLabelFields ?? [])],
        filters: Object.keys(filters).length ? filters : undefined,
        limit_page_length: 500,
      }),
    enabled: enabled && depsSatisfied,
  })
}

function linkOptionLabel(spec: FieldSpec, opt: Record<string, unknown> & { name: string }): string {
  if (!spec.linkLabelFields?.length) return opt.name
  const composed = spec.linkLabelFields
    .map((f) => opt[f])
    .filter(Boolean)
    .join(" ")
  return composed || opt.name
}

/** Row-styled field renderer for finance screens, mirroring DynamicField
 * but using the finance-ui design tokens instead of shadcn Form/Input.*/
export function FinanceDynamicField<T extends FieldValues>({
  control,
  spec,
}: {
  control: Control<T>
  spec: FieldSpec
}) {
  const watchedFilterValues = useWatch({
    control,
    name: (spec.linkFilterFields ?? []) as Path<T>[],
  }) as unknown[]
  const watchedMap = (spec.linkFilterFields ?? []).reduce<Record<string, unknown>>((acc, key, i) => {
    acc[key] = watchedFilterValues[i]
    return acc
  }, {})

  const linkDropdownQuery = useLinkDropdownOptions(spec, watchedMap)
  const depsSatisfied = (spec.linkFilterFields ?? []).every((key) => !!watchedMap[key])

  return (
    <Controller
      control={control}
      name={spec.fieldname as Path<T>}
      rules={{ required: spec.required ? `${spec.label} is required` : false }}
      render={({ field, fieldState }) => (
        <FinancePropertyRow label={`${spec.label}${spec.required ? " *" : ""}`}>
          <>
            {spec.fieldtype === "Check" ? (
              <input
                type="checkbox"
                checked={!!field.value}
                onChange={(e) => field.onChange(e.target.checked)}
                disabled={spec.readOnly}
                className="h-4 w-4 rounded border-border"
              />
            ) : spec.fieldtype === "Link" && spec.dropdown ? (
              <LinkCombobox
                spec={spec}
                value={field.value as string | undefined}
                onChange={field.onChange}
                options={linkDropdownQuery.data ?? []}
                isLoading={linkDropdownQuery.isLoading}
                disabled={spec.readOnly || (!!spec.linkFilterFields?.length && !depsSatisfied)}
                placeholder={
                  !depsSatisfied && spec.linkFilterFields?.length
                    ? `Select ${spec.linkFilterFields.join(" & ")} first`
                    : undefined
                }
              />
            ) : spec.fieldtype === "Select" ? (
              <select
                className={`rounded border border-border ${financeRowSelect}`}
                value={(field.value as string | undefined) ?? ""}
                onChange={(e) => field.onChange(e.target.value)}
                disabled={spec.readOnly}
              >
                <option value="" />
                {(spec.options ?? "")
                  .split("\n")
                  .filter(Boolean)
                  .map((opt) => (
                    <option key={opt} value={opt}>
                      {opt}
                    </option>
                  ))}
              </select>
            ) : (
              <input
                type={
                  spec.fieldtype === "Date"
                    ? "date"
                    : spec.fieldtype === "Datetime"
                      ? "datetime-local"
                      : spec.fieldtype === "Int" || spec.fieldtype === "Float" || spec.fieldtype === "Currency"
                        ? "number"
                        : "text"
                }
                readOnly={spec.readOnly}
                className={`rounded border border-border ${spec.readOnly ? "bg-muted text-muted-foreground" : ""} ${financeRowInput}`}
                value={(field.value as string | number | undefined) ?? ""}
                onChange={(e) => field.onChange(e.target.value)}
              />
            )}
            {spec.description && !fieldState.error && (
              <p className="mt-1 text-xs text-muted-foreground">{spec.description}</p>
            )}
            {fieldState.error && (
              <p className="mt-1 text-xs text-destructive">{fieldState.error.message}</p>
            )}
          </>
        </FinancePropertyRow>
      )}
    />
  )
}