"use client"

import { useQuery } from "@tanstack/react-query"
import type { Control, FieldValues, Path } from "react-hook-form"
import { Controller, useWatch } from "react-hook-form"
import type { FieldSpec } from "@/lib/forms/types"
import { frappe } from "@/lib/frappe"
import { financeRowInput, financeRowSelect } from "@/lib/finance-ui"
import { FinancePropertyRow } from "@/components/finance/FinancePropertyPanel"

/**
 * Options for a Link field spec'd with `dropdown: true` — the list of
 * records of its target doctype (`spec.options`), rather than the usual
 * type-the-exact-name Data input. Supports:
 *  - `linkStaticFilters` / `linkFilterFields`: narrows the fetched records
 *    (e.g. parent_account filtered to is_group=1 + the currently-selected
 *    company/root_type).
 *  - `linkLabelFields`: composes a readable option label from extra fields
 *    on the target doctype, for doctypes (like SMS Student) whose `name`
 *    is an opaque autogenerated hash rather than something human-readable.
 */
function useLinkDropdownOptions(spec: FieldSpec, watchedFilterValues: Record<string, unknown>) {
  const enabled = spec.fieldtype === "Link" && !!spec.dropdown && !!spec.options

  const filters: Record<string, unknown> = { ...(spec.linkStaticFilters ?? {}) }
  for (const key of spec.linkFilterFields ?? []) {
    const v = watchedFilterValues[key]
    if (v) filters[key] = v
  }
  const depsSatisfied = (spec.linkFilterFields ?? []).every((key) => !!watchedFilterValues[key])

  return useQuery({
    queryKey: ["Link", "dropdown-options", spec.options, filters, spec.linkLabelFields],
    queryFn: () =>
      frappe.list<Record<string, unknown> & { name: string }>(spec.options as string, {
        fields: ["name", ...(spec.linkLabelFields ?? [])],
        filters: Object.keys(filters).length ? filters : undefined,
        limit_page_length: 500,
      }),
    enabled: enabled && depsSatisfied,
  })
}

function linkOptionLabel(spec: FieldSpec, opt: Record<string, unknown> & { name: string }): string {
  if (!spec.linkLabelFields?.length) return opt.name
  const composed = spec.linkLabelFields
    .map((f) => opt[f])
    .filter(Boolean)
    .join(" ")
  return composed || opt.name
}

/** Row-styled field renderer for finance screens, mirroring DynamicField
 * but using the finance-ui design tokens instead of shadcn Form/Input. */
export function FinanceDynamicField<T extends FieldValues>({
  control,
  spec,
}: {
  control: Control<T>
  spec: FieldSpec
}) {
  const watchedFilterValues = useWatch({
    control,
    name: (spec.linkFilterFields ?? []) as Path<T>[],
  }) as unknown[]
  const watchedMap = (spec.linkFilterFields ?? []).reduce<Record<string, unknown>>((acc, key, i) => {
    acc[key] = watchedFilterValues[i]
    return acc
  }, {})

  const linkDropdownQuery = useLinkDropdownOptions(spec, watchedMap)
  const depsSatisfied = (spec.linkFilterFields ?? []).every((key) => !!watchedMap[key])

  return (
    <Controller
      control={control}
      name={spec.fieldname as Path<T>}
      rules={{ required: spec.required ? `${spec.label} is required` : false }}
      render={({ field, fieldState }) => (
        <FinancePropertyRow label={`${spec.label}${spec.required ? " *" : ""}`}>
          <>
            {spec.fieldtype === "Check" ? (
              <input
                type="checkbox"
                checked={!!field.value}
                onChange={(e) => field.onChange(e.target.checked)}
                disabled={spec.readOnly}
                className="h-4 w-4 rounded border-zinc-300"
              />
            ) : spec.fieldtype === "Link" && spec.dropdown ? (
              <select
                className={`rounded border border-zinc-200 ${financeRowSelect}`}
                value={(field.value as string | undefined) ?? ""}
                onChange={(e) => field.onChange(e.target.value)}
                disabled={spec.readOnly || (!!spec.linkFilterFields?.length && !depsSatisfied)}
              >
                <option value="">
                  {!depsSatisfied && spec.linkFilterFields?.length
                    ? `Select ${spec.linkFilterFields.join(" & ")} first`
                    : linkDropdownQuery.isLoading
                      ? "Loading…"
                      : `Select ${spec.label}`}
                </option>
                {(linkDropdownQuery.data ?? []).map((opt) => (
                  <option key={opt.name} value={opt.name}>
                    {linkOptionLabel(spec, opt)}
                  </option>
                ))}
              </select>
            ) : spec.fieldtype === "Select" ? (
              <select
                className={`rounded border border-zinc-200 ${financeRowSelect}`}
                value={(field.value as string | undefined) ?? ""}
                onChange={(e) => field.onChange(e.target.value)}
                disabled={spec.readOnly}
              >
                <option value="" />
                {(spec.options ?? "")
                  .split("\n")
                  .filter(Boolean)
                  .map((opt) => (
                    <option key={opt} value={opt}>
                      {opt}
                    </option>
                  ))}
              </select>
            ) : (
              <input
                type={
                  spec.fieldtype === "Date"
                    ? "date"
                    : spec.fieldtype === "Datetime"
                      ? "datetime-local"
                      : spec.fieldtype === "Int" || spec.fieldtype === "Float" || spec.fieldtype === "Currency"
                        ? "number"
                        : "text"
                }
                readOnly={spec.readOnly}
                className={`rounded border border-zinc-200 ${spec.readOnly ? "bg-zinc-50 text-zinc-500" : ""} ${financeRowInput}`}
                value={(field.value as string | number | undefined) ?? ""}
                onChange={(e) => field.onChange(e.target.value)}
              />
            )}
            {spec.description && !fieldState.error && (
              <p className="mt-1 text-xs text-zinc-500">{spec.description}</p>
            )}
            {fieldState.error && (
              <p className="mt-1 text-xs text-red-600">{fieldState.error.message}</p>
            )}
          </>
        </FinancePropertyRow>
      )}
    />
  )
}
