"use client"

import { useState, type ReactNode } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { toast } from "sonner"
import {
  ChevronsLeft,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  PlusIcon,
  PencilIcon,
  Trash2Icon,
  SearchIcon,
} from "lucide-react"

import { frappe, getErrorMessage } from "@/lib/frappe"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

interface RoomRow {
  name: string
  room_number: string | null
  building: string | null
  seating_capacity: string | null
}

interface RoomFormState {
  room_number: string
  building: string
  seating_capacity: string
}

const BLANK_FORM: RoomFormState = {
  room_number: "",
  building: "",
  seating_capacity: "",
}

function docToForm(doc: RoomRow): RoomFormState {
  return {
    room_number: doc.room_number ?? "",
    building: doc.building ?? "",
    seating_capacity: doc.seating_capacity ?? "",
  }
}

/** Small local label+control wrapper — only consumer is this component. */
function Field({ id, label, children }: { id: string; label: string; children: ReactNode }) {
  return (
    <div className="grid gap-1.5">
      <label htmlFor={id}>{label}</label>
      {children}
    </div>
  )
}

/**
 * "Rooms" (Maintenance tab): a Room master browsed one record at a time —
 * read-only until Edit or Add is pressed, same Add/Edit/Delete/Save/Cancel
 * shape as Courses Offered/Curriculum Offered. Room's own `name` is a
 * system-autogenerated series (HTL-ROOM-YYYY-#####), not user-facing, so
 * unlike Program (whose course_code effectively doubles as an id) nothing
 * here needs to be locked once a record already exists.
 *
 * Room's required title field (room_name) has no counterpart in this
 * screen's three requested fields (Room Number/Building/Capacity) - it's
 * mirrored from room_number on save rather than surfaced as a fourth field,
 * since Classes Offered already displays room_name/room_number together
 * elsewhere (see classes.tsx) and this keeps that working without asking
 * the registrar to fill in a name that's redundant with the number here.
 */
export default function Rooms() {
  const queryClient = useQueryClient()

  const roomsQuery = useQuery({
    queryKey: ["Room", "list", "rooms"],
    queryFn: () =>
      frappe.list<RoomRow>("Room", {
        fields: ["name", "room_number", "building", "seating_capacity"],
        order_by: "room_number asc",
        limit_page_length: 500,
      }),
  })

  const rooms = roomsQuery.data ?? []

  const [initialized, setInitialized] = useState(false)
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null)
  const [pendingSelectName, setPendingSelectName] = useState<string | null>(null)
  const [syncedName, setSyncedName] = useState<string | undefined>(undefined)
  const [form, setForm] = useState<RoomFormState>(BLANK_FORM)
  const [isEditing, setIsEditing] = useState(false)
  const [findQuery, setFindQuery] = useState("")
  const [findOpen, setFindOpen] = useState(false)

  if (!initialized && rooms.length > 0) {
    setInitialized(true)
    setSelectedIndex(0)
  }

  const selected = selectedIndex !== null ? rooms[selectedIndex] : null

  if (selected && selected.name !== syncedName) {
    setSyncedName(selected.name)
    setForm(docToForm(selected))
  }

  if (pendingSelectName) {
    const idx = rooms.findIndex((r) => r.name === pendingSelectName)
    if (idx !== -1) {
      setSelectedIndex(idx)
      setPendingSelectName(null)
    }
  }

  function handleAdd() {
    setSelectedIndex(null)
    setSyncedName(undefined)
    setForm(BLANK_FORM)
    setIsEditing(true)
  }

  function handleEdit() {
    if (!selected) return
    setForm(docToForm(selected))
    setIsEditing(true)
  }

  function handleCancel() {
    if (selected) {
      setForm(docToForm(selected))
    } else {
      setForm(BLANK_FORM)
    }
    setIsEditing(false)
  }

  function selectRecord(idx: number) {
    if (idx < 0 || idx >= rooms.length) return
    setSelectedIndex(idx)
  }

  const findMatches = findQuery.trim()
    ? rooms.filter(
        (r) =>
          r.room_number?.toLowerCase().includes(findQuery.trim().toLowerCase()) ||
          r.building?.toLowerCase().includes(findQuery.trim().toLowerCase())
      )
    : []

  function jumpToRoom(name: string) {
    const idx = rooms.findIndex((r) => r.name === name)
    if (idx !== -1) setSelectedIndex(idx)
    setFindOpen(false)
  }

  function handleFind() {
    const query = findQuery.trim().toLowerCase()
    if (!query) return
    const idx = rooms.findIndex(
      (r) => r.room_number?.toLowerCase().includes(query) || r.building?.toLowerCase().includes(query)
    )
    if (idx === -1) {
      toast.info(`No room found matching "${findQuery}"`)
      return
    }
    setSelectedIndex(idx)
    setFindOpen(false)
  }

  const saveMutation = useMutation({
    mutationFn: () => {
      const payload = {
        room_name: form.room_number,
        room_number: form.room_number || undefined,
        building: form.building || undefined,
        seating_capacity: form.seating_capacity || undefined,
      }
      return selected
        ? frappe.updateDoc<RoomRow>("Room", selected.name, payload)
        : frappe.createDoc<RoomRow>("Room", payload)
    },
    onSuccess: async (saved) => {
      toast.success("Room saved")
      setPendingSelectName(saved.name)
      setIsEditing(false)
      await queryClient.invalidateQueries({ queryKey: ["Room"] })
    },
    onError: (error) => toast.error(`Could not save room: ${getErrorMessage(error)}`),
  })

  const deleteMutation = useMutation({
    mutationFn: () => frappe.deleteDoc("Room", selected!.name),
    onSuccess: async () => {
      toast.success("Room deleted")
      setSelectedIndex(null)
      setSyncedName(undefined)
      setForm(BLANK_FORM)
      await queryClient.invalidateQueries({ queryKey: ["Room"] })
    },
    onError: (error) => toast.error(`Could not delete room: ${getErrorMessage(error)}`),
  })

  const canSave = !!form.room_number && !saveMutation.isPending

  return (
    <div className="rounded-2xl border border-black/20 h-full p-6 flex flex-col gap-5 overflow-y-auto">
      <div className="flex flex-wrap items-center gap-2 border-b border-black/10 pb-4">
        <Button type="button" disabled={isEditing} onClick={handleAdd}>
          <PlusIcon /> Add
        </Button>
        <Button type="button" variant="outline" disabled={isEditing || !selected} onClick={handleEdit}>
          <PencilIcon /> Edit
        </Button>
        <Button
          type="button"
          variant="outline"
          disabled={isEditing || !selected || deleteMutation.isPending}
          onClick={() => deleteMutation.mutate()}
        >
          <Trash2Icon /> Delete
        </Button>

        <div
          className="relative flex items-start gap-2 ml-4"
          onBlur={(e) => {
            if (!e.currentTarget.contains(e.relatedTarget)) setFindOpen(false)
          }}
        >
          <Input
            placeholder="Find by room number or building…"
            className="w-64"
            value={findQuery}
            disabled={isEditing}
            onChange={(e) => {
              setFindQuery(e.target.value)
              setFindOpen(true)
            }}
            onFocus={() => setFindOpen(true)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault()
                handleFind()
              } else if (e.key === "Escape") {
                setFindOpen(false)
              }
            }}
          />
          <Button type="button" variant="outline" size="icon" disabled={isEditing} onClick={handleFind}>
            <SearchIcon />
          </Button>

          {findOpen && findQuery.trim() && !isEditing && (
            <div className="absolute top-full left-0 z-20 mt-1 w-64 rounded-lg bg-popover text-popover-foreground shadow-md ring-1 ring-foreground/10 max-h-64 overflow-y-auto p-1">
              {findMatches.length === 0 ? (
                <div className="p-2 text-sm text-muted-foreground">No matches.</div>
              ) : (
                findMatches.map((r) => (
                  <button
                    key={r.name}
                    type="button"
                    className="w-full text-left rounded-md px-2.5 py-1.5 text-sm hover:bg-accent hover:text-accent-foreground"
                    onClick={() => jumpToRoom(r.name)}
                  >
                    {r.room_number ?? r.name}
                    {r.building ? ` — ${r.building}` : ""}
                  </button>
                ))
              )}
            </div>
          )}
        </div>

        {isEditing && (
          <div className="ml-auto flex gap-2">
            <Button type="button" disabled={!canSave} onClick={() => saveMutation.mutate()}>
              {saveMutation.isPending ? "Saving…" : "Save"}
            </Button>
            <Button type="button" variant="outline" onClick={handleCancel}>
              Cancel
            </Button>
          </div>
        )}
      </div>

      <div className="grid gap-4 md:grid-cols-2 max-w-2xl">
        <Field id="room-number" label="Room Number">
          <Input
            id="room-number"
            value={form.room_number}
            disabled={!isEditing}
            onChange={(e) => setForm((prev) => ({ ...prev, room_number: e.target.value }))}
          />
        </Field>
        <Field id="room-building" label="Building">
          <Input
            id="room-building"
            value={form.building}
            disabled={!isEditing}
            onChange={(e) => setForm((prev) => ({ ...prev, building: e.target.value }))}
          />
        </Field>
        <Field id="room-capacity" label="Capacity">
          <Input
            id="room-capacity"
            type="number"
            value={form.seating_capacity}
            disabled={!isEditing}
            onChange={(e) => setForm((prev) => ({ ...prev, seating_capacity: e.target.value }))}
          />
        </Field>
      </div>

      <div className="flex items-center justify-between border-t border-black/10 pt-4 mt-auto">
        <div className="text-sm text-muted-foreground">
          {selectedIndex !== null && rooms.length > 0
            ? `Record ${selectedIndex + 1} of ${rooms.length}`
            : "New Room"}
        </div>
        <div className="flex gap-2">
          <Button
            type="button"
            size="icon-sm"
            variant="outline"
            disabled={isEditing || selectedIndex === null || selectedIndex === 0}
            onClick={() => selectRecord(0)}
          >
            <ChevronsLeft />
          </Button>
          <Button
            type="button"
            size="icon-sm"
            variant="outline"
            disabled={isEditing || selectedIndex === null || selectedIndex === 0}
            onClick={() => selectRecord((selectedIndex ?? 0) - 1)}
          >
            <ChevronLeft />
          </Button>
          <Button
            type="button"
            size="icon-sm"
            variant="outline"
            disabled={isEditing || selectedIndex === null || selectedIndex >= rooms.length - 1}
            onClick={() => selectRecord((selectedIndex ?? -1) + 1)}
          >
            <ChevronRight />
          </Button>
          <Button
            type="button"
            size="icon-sm"
            variant="outline"
            disabled={isEditing || selectedIndex === null || selectedIndex >= rooms.length - 1}
            onClick={() => selectRecord(rooms.length - 1)}
          >
            <ChevronsRight />
          </Button>
        </div>
      </div>
    </div>
  )
}
